### ISSUE TITLE
Ubuntu20.10 are not available

### ISSUE THREAD

**Issue by Allojpass** [feiskyer/ebpf-apps#3]
clang -g -O2 -Wall -I. -c xdp-proxy.c -o xdp-proxy.o
clang -Wall -O2 -g xdp-proxy.o -static -lbpf -lelf -lz -o xdp-proxy

These two instructions cannot run

xdp-proxy.c:54:2: warning: implicit declaration of function 'LIBBPF_OPTS' is invalid in C99 [-Wimplicit-function-declaration]
        LIBBPF_OPTS(bpf_xdp_attach_opts, attach_opts);
        ^
xdp-proxy.c:54:14: error: use of undeclared identifier 'bpf_xdp_attach_opts'
        LIBBPF_OPTS(bpf_xdp_attach_opts, attach_opts);
                    ^
xdp-proxy.c:54:35: error: use of undeclared identifier 'attach_opts'
        LIBBPF_OPTS(bpf_xdp_attach_opts, attach_opts);
                                         ^
xdp-proxy.c:55:8: warning: implicit declaration of function 'bpf_xdp_attach' is invalid in C99 [-Wimplicit-function-declaration]
        err = bpf_xdp_attach(ifindex, prog_id, xdp_flags, &attach_opts);
              ^
xdp-proxy.c:55:53: error: use of undeclared identifier 'attach_opts'
        err = bpf_xdp_attach(ifindex, prog_id, xdp_flags, &attach_opts);
                                                           ^
xdp-proxy.c:67:2: warning: implicit declaration of function 'bpf_xdp_detach' is invalid in C99 [-Wimplicit-function-declaration]
        bpf_xdp_detach(ifindex, xdp_flags, &attach_opts);
        ^
xdp-proxy.c:67:38: error: use of undeclared identifier 'attach_opts'
        bpf_xdp_detach(ifindex, xdp_flags, &attach_opts);
                                            ^
3 warnings and 4 errors generated.

**Comment by feiskyer** [comment]
please build and install libbpf manually
